baseURL = "/"
publishDir = "../docs"
languageCode = "en-us"

title = "Cloud Native Buildpack Documentation"
theme = "buildpacks"

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "Home"
  url        = "/"
  weight     = 1

  [[menu.main]]
  identifier = "docs"
  name       = "Docs"
  url        = "/docs"
  weight     = 2

  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "https://medium.com/buildpacks"
  weight     = 3
