name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to compare changes

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: content/**/*.md  # Only check markdown files in the content directory
          separator: ","

      - uses: errata-ai/vale-action@v2.1.1
        if: steps.changed-files.outputs.any_changed == 'true'
        with: 
          fail_on_error: true
          token: ${{secrets.GITHUB_TOKEN}}
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
